addSbtPlugin("ch.epfl.lamp"      % "sbt-dotty"       % "0.5.1")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"      % "4.1.1")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"  % "1.5.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"    % "2.4.2")
